import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { loaders } from "@/data/loaders";
import { validateApiResponse } from "@/lib/error-handler";
import Header from "@/components/custom/header";
import Footer from "@/components/custom/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});



export async function generateMetadata(): Promise<Metadata> {
  const metadata =await loaders.getMetaData();
  return {
    title: metadata?.data?.title ??  "NextJS and NestJS Review",
    description: "Generated by NextJS and NestJS Review",
  };
}




export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const globalDataResponse =await loaders.getGlobalData();
  const globalData = validateApiResponse(globalDataResponse, "Global Data");
  console.dir(globalData,  {depth :null});

  return (
    <html lang="ko">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Header data={globalData?.header} />
        {children}
        <Footer data={globalData?.footer} />
      </body>
    </html>
  );
}
