import type { Metadata } from "next";
import "./globals.css";
import { loaders } from "@/data/loaders";
import { validateApiResponse } from "@/lib/error-handler";
import Footer from "@/components/custom/footer";
import { Header } from "@/components/custom/header";
import { Toaster } from "@/components/ui/sonner";


export async function generateMetadata(): Promise<Metadata> {
  const metadata = await loaders.getMetaData();
  return {
    title: metadata?.data?.title ?? "NextJS and NestJS Review",
    description: "Generated by NextJS and NestJS Review",
  };
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const globalDataResponse = await loaders.getGlobalData();
  const globalData = validateApiResponse(globalDataResponse, "Global Data");
  console.dir(globalData, { depth: null });

  return (
    <html lang="ko">
       <body>
        <Toaster position="bottom-center" />
        <Header data={globalData?.header} />
        {children}
        <Footer data={globalData?.footer} />
      </body>
    </html>
  );
}
